apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c8w6qo9tt-python 
  janus-idp.io/tekton: c8w6qo9tt-python
  backstage.io/kubernetes-id: c8w6qo9tt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c8w6qo9tt-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml